# Generated by Django 5.1.3 on 2024-11-27 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_smart', '0003_remove_order_email_remove_order_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='flow_order',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
