# Generated by Django 5.1.3 on 2024-11-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_smart', '0004_order_flow_order_order_payment_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ciudad',
            field=models.CharField(default='Santiago', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='comuna',
            field=models.CharField(default='Santiago', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('flow', 'Pago con Flow'), ('transfer', 'Transferencia Bancaria')], default='unknown', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='region',
            field=models.CharField(default='metropolitana', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(choices=[('pickup', 'Retiro en tienda'), ('starken', 'Envío Starken')], max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
