# Generated by Django 5.1.3 on 2024-11-28 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_smart', '0006_guestorder_alter_order_order_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completado'), ('failed', 'Fallido'), ('refunded', 'Reembolsado')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('flow', 'Flow'), ('transfer', 'Transferencia Bancaria')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(choices=[('pickup', 'Retiro en tienda'), ('starken', 'Envío Starken')], default='pickup', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('shipped', 'Enviado'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordertracking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('shipped', 'Enviado'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado')], max_length=20),
        ),
    ]
