# Generated by Django 5.1.2 on 2024-12-04 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_smart', '0007_order_payment_status_alter_order_order_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='order',
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, default='', unique=True),
        ),
    ]
