name: Django CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
        cache: 'pip'
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install Django==5.0
        python -m pip install -r requirements.txt
      continue-on-error: true
    
    - name: Create Directories
      run: |
        mkdir -p staticfiles
        mkdir -p media
    
    - name: Collect Static Files
      run: |
        python manage.py collectstatic --noinput
      env:
        DJANGO_SETTINGS_MODULE: ecommerce.settings
        DEBUG: "True"
        SECRET_KEY: "your-secret-key-here"
    
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./staticfiles
        force_orphan: true
