name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.13'
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create .env file
      run: |
        echo "DEBUG=True" >> .env
        echo "SECRET_KEY=your-secret-key-for-testing" >> .env
        # Agrega otras variables de entorno necesarias
    
    - name: Run Migrations
      run: |
        python manage.py makemigrations
        python manage.py migrate
    
    - name: Run Tests
      run: |
        python manage.py test
